spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: ${PASSDB:123}

springdoc:
  api-docs:
    path: /mercado-livro-api-docs
  swagger-ui:
    path: /mercado-livro.html
    operations-sorter: method
    url: /mercado-livro-api-docs
    disable-swagger-default-url: true